[package]
name = "bex-staking-rust-helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
dotenv = "0.15"
ethers = "2.0"
tokio = { version = "1", features = ["full"] }
